name=["bino", "treku", "yoeman", "cobnaldo", "federal"]
print(name)
print(f'I would like to invite you to diner, {name[0].title()}.')
print(f'I would like to invite you to diner, {name[1].title()}.')
print(f'I would like to invite you to diner, {name[2].title()}.')
print(f'I would like to invite you to diner, {name[3].title()}.')
print(f'I would like to invite you to diner, {name[4].title()}.')
print("bino, treku amd cobnaldo can't make it")
name.remove("bino")
name.remove("treku")
name.remove("cobnaldo")
print(name)
name.insert(0, "bonti")
name.insert(1, "mame down")
name.insert (3, "aha")
print(name)
print("I can invite only two people for dinner.")
nigga_1 = name.pop(3)
nigga_2=name.pop(2)
nigga_3= name.pop(1)
print(name)
print(f"Sorry I can't invite {nigga_1} to dinner anymore")
print(f"Sorry I can't invite {nigga_2} to dinner anymore")
print(f"Sorry I can't invite {nigga_3} to dinner anymore")
print(name)
print(f"You are still invited to the dinner,{name[0].title()}")
print(f"You are still invited to the dinner,{name[1].title()}")
del name[0]
del name[0]
print(name)